services:
    nginx:
        image: nginx
        build:
            context: ./nginx
            dockerfile: dockerfile-nginx
        ports:
            - 8080:8080
        restart: always

    api:
        depends_on:
            - nginx
        image: api
        build: ./flask
        restart: always